### ISSUE TITLE
hugo version command "Hugo not installed or path not set"

### ISSUE THREAD

**Issue by locolupo** [akmittal/Hugofy-sublime#1]
Hi,

i've tried to use the hugofy plugin with my sublimetext.

`hugofy: Version` causes the following error: "Hugo not installed or path not set"

`which hugo`

```
/usr/local/bin/hugo
```

then i've checked the sourcecode:

```
out=subprocess.check_output("hugo version",stderr=subprocess.STDOUT,universal_newlines=True)
```

``` python
>>> import subprocess
>>> subprocess.check_output("hugo version",stderr=subprocess.STDOUT,universal_newlines=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

``` python
>>>import subprocess
subprocess.check_output(["hugo", "version"],stderr=subprocess.STDOUT,universal_newlines=True)
'Hugo Static Site Generator v0.14 BuildDate: 2015-09-22T13:00:01+02:00\n'
```

this worked better for me, can you reproduce this issue?

MacOS 10.11.1, Python 2.7.10

if you like i can provide a PR

**Comment by akmittal** [comment]
I have a windows machine with Python 3.x so can't reproduce. 
Provide a PR.

**Comment by maireh** [comment]
This is a bug with Sublime Text on mac and not in Hugofy. There is an easy workaround: always launch sublime from your terminal and never from the launcher.

Details - sublime text does not use the system path in ~/.profile. Instead it uses its own path. If you use homebrew to install Hugo then it won't work. I could not figure out how to fix sublime so instead I set up sublime to run from the terminal.

In Bash type:
 ln -s "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" /usr/local/bin/sublime

Alternately add the following line to ~/.profile (might be ~/.bash_profile on other OSX versions):
export PATH="/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl:$PATH"
