### ISSUE TITLE
Not working on OSX

### ISSUE THREAD

**Issue by mubix** [akmittal/Hugofy-sublime#3]
Installed FixMacPath via https://github.com/int3h/SublimeFixMacPath so that Sublime could see the hugo binary but there were still uses

**Comment by akmittal** [comment]
you can run hugo command from terminal?

**Comment by nmistry** [comment]
I am not able to invoke hugo either.   It is in my path, and i can run it... 

sublime text 3 console spits this out: 

```
reloading settings Packages/User/hugofy.sublime-settings
Traceback (most recent call last):
  File "Hugofy in /Users/nmistry/Library/Application Support/Sublime Text 3/Installed Packages/Hugofy.sublime-package", line 23, in on_done
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'hugo new time-well-spent.md'
```

**Comment by akmittal** [comment]
@nmistry Is the Directory path correct in plugin settings?

**Comment by cuscada** [comment]
Hi
I use osx, and I was able to invoke hugofy CMD+SHIFT+P in Sublime 3.
I have clicked Hugo new site. Then.. nothing happen. Where is the new site located at??
Thanks.

**Comment by akmittal** [comment]
@DavyDev  You should  check`Preferences > Package Settings > Hugofy` check Default settings. Then overwrite Directory key in `Preferences > Package Settings > Hugofy >Settings - User`

**Comment by maksim77** [comment]
PR #7 will fix it.

**Comment by akmittal** [comment]
Merged pull request, closing issue.
